from django.db import models

# Create your models here.
class Renta(models.Model):
		Cod_cliente = models.IntegerField(primary_key=True)
		Dummy = models.IntegerField()
		Nombre = models.CharField(max_length=100)
		Fecha = models.DateField()
		Plazo = models.IntegerField()
		NombrePlan = models.CharField(max_length=100)
		BolsaPrincipal = models.FloatField()
		Móviles = models.IntegerField()
		SuscripciónMóvil = models.FloatField()
		MaxMóviles = models.IntegerField()
		E1s = models.IntegerField()
		SIP = models.IntegerField()
		Planes1GBIncluido = models.IntegerField()
		Planes2GBIncluido = models.IntegerField()
		Planes5GBIncluido = models.IntegerField()
		Planes10GBInlcuido = models.IntegerField()
		Planes20GBIncluido = models.IntegerField()
		Planes1GBAdicional = models.IntegerField()
		Planes2GBAdicional = models.IntegerField()
		Planes5GBAdicional = models.IntegerField()
		Planes10GBAdicional = models.IntegerField()
		Planes20GBAdicional = models.IntegerField()
		SubsidioOtorgad = models.FloatField()
		TotalQSuscripciones = models.FloatField()
		TotalQPlanesDatos = models.FloatField()
		RentaTotalMensualQ = models.FloatField()