# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('Cod_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('Dummy', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Plazo', models.IntegerField()),
                ('NombrePlan', models.CharField(max_length=100)),
                ('BolsaPrincipal', models.IntegerField()),
                ('Móviles', models.IntegerField()),
                ('SuscripciónMóvil', models.IntegerField()),
                ('MaxMóviles', models.IntegerField()),
                ('E1s', models.IntegerField()),
                ('SIP', models.IntegerField()),
                ('Planes1GBIncluido', models.IntegerField()),
                ('Planes2GBIncluido', models.IntegerField()),
                ('Planes5GBIncluido', models.IntegerField()),
                ('Planes10GBInlcuido', models.IntegerField()),
                ('Planes20GBIncluido', models.BigIntegerField()),
                ('Planes1GBAdicional', models.IntegerField()),
                ('Planes2GBAdicional', models.IntegerField()),
                ('Planes5GBAdicional', models.IntegerField()),
                ('Planes10GBAdicional', models.IntegerField()),
                ('Planes20GBAdicional', models.IntegerField()),
                ('SubsidioOtorgad', models.IntegerField()),
                ('TotalQSuscripciones', models.IntegerField()),
                ('TotalQPlanesDatos', models.IntegerField()),
                ('RentaTotalMensualQ', models.IntegerField()),
            ],
        ),
    ]
