# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='BolsaPrincipal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='renta',
            name='Planes20GBIncluido',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='renta',
            name='RentaTotalMensualQ',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='renta',
            name='SubsidioOtorgad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='renta',
            name='SuscripciónMóvil',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='renta',
            name='TotalQPlanesDatos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='renta',
            name='TotalQSuscripciones',
            field=models.FloatField(),
        ),
    ]
